version: "3.7"

services:
  database:
    image: postgres
    container_name: layback_dashboard_api_postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=layback
    volumes:
      - pgdata:/data/postgres


  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6377:6379
    container_name: layback_dashboard_api_redis



  # app:
  #   build: .
  #   container_name: layback_backend
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database


volumes:
  pgdata:
    driver: local
